### ISSUE TITLE
test-external for scenarios other than east/west

### ISSUE THREAD

**Issue by pwright** [skupperproject/skewer#1]
If you want to create an example for any number of sites other than 2 (east, west), and you want to test using external clusters, you need to explicitly list those sites in the `.planofile`, for example, if you want to test a four site example, you might list:

```
@command
def test_external(app, west_kubeconfig, east_kubeconfig, north_kubeconfig, south_kubeconfig):
    """
    Test the example against external clusters
    """
    generate_readme("skewer.yaml", make_temp_file())
    run_steps_external("skewer.yaml", west=west_kubeconfig, east=east_kubeconfig, north=north_kubeconfig, south=south_kubeconfig)

```
@ssorj am I correct, and is this best addressed by putting the text above into README?

**Comment by ssorj** [comment]
@pwright yes, you are correct.  I'll add that to the readme.

**Comment by ssorj** [comment]
I've now changed the run-external command to take a positional list of kubeconfigs.  They are applied in order to the sites in the supplied skewer.yaml.  The default implementation should work without being overridden, so I hope you can just use the symlinked .planofile and not create your own copy.
